{"name": "test_login_success", "status": "broken", "statusDetails": {"message": "KeyError: 'date3'", "trace": "@pytest.fixture(scope='session',autouse=True)\n    def session_fixtrue10():\n        path='/api/learning/v3/judge'\n>       date=date1[\"date3\"]\nE       KeyError: 'date3'\n\nconftest.py:80: KeyError"}, "start": 1586522703381, "stop": 1586522703381, "uuid": "67a3e72d-3f35-4f22-82d1-992c326dc3cf", "historyId": "b40641d31f013d71b08e9edead2f906b", "testCaseId": "40328625064c5c8b47b3abdd23fe1487", "fullName": "testcases.test_login.Test_login#test_login_success", "labels": [{"name": "story", "value": "登录成功"}, {"name": "feature", "value": "登录成功"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-938U3RR"}, {"name": "thread", "value": "4472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}