{"uuid": "397a0830-b0c2-4082-9359-b8598c3adbab", "children": ["d47b39bd-4df3-47e9-b1b0-8250acac35d6", "5a0df893-e2ad-441e-9b21-f1fc9f5fbfc0", "aeed47d9-df2b-4f66-bdcb-3ba6324c64dc", "6528114e-7202-4321-b948-ab761c4bb494", "5d6ed8c9-50d1-44e6-9ba4-9d0a4a1979c7", "c6b7ba25-df40-4db6-af3f-7b29db060ccb", "137def91-2811-4f43-855e-6915c21f1bd5", "0a6fa660-d999-4901-b309-9143dd89039e", "ef9c0c17-679b-4214-8cf5-e476cab3e0a9", "ebd2e9e3-f334-45f0-b2d3-af851a69c064", "bb628c02-8ed1-4d7d-9b6b-bf312a07b088", "025e7411-bc81-4c43-b73b-e35c87e0b21a"], "befores": [{"name": "session_fixtrue10", "status": "broken", "statusDetails": {"message": "TypeError: unhashable type: 'dict'\n", "trace": "  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\PyCharm\\PycharmProjects\\requests\\conftest.py\", line 80, in session_fixtrue10\n    date4=date1[date1]\n"}, "start": 1586521603610, "stop": 1586521603610}], "start": 1586521603610, "stop": 1586521603829}