{"name": "test_login_fail", "status": "broken", "statusDetails": {"message": "TypeError: unhashable type: 'dict'", "trace": "@pytest.fixture(scope='session',autouse=True)\n    def session_fixtrue10():\n        path='/api/learning/v3/judge'\n>       date4=date1[date1]\nE       TypeError: unhashable type: 'dict'\n\nconftest.py:80: TypeError"}, "start": 1586521603813, "stop": 1586521603813, "uuid": "bb628c02-8ed1-4d7d-9b6b-bf312a07b088", "historyId": "faaf16db42328d14a17b9143c87594f2", "testCaseId": "4d2fd9c86f5ffb069562c8495780fca5", "fullName": "testcases.test_login.Test_login#test_login_fail", "labels": [{"name": "story", "value": "登录失败"}, {"name": "feature", "value": "登录成功"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-938U3RR"}, {"name": "thread", "value": "11124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}